# Generated by Django 3.0 on 2020-05-13 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('idpeca', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.FloatField()),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('idDemanda', models.AutoField(primary_key=True, serialize=False)),
                ('rua', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
                ('pecas', models.ManyToManyField(to='dempeca.Peca')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dempeca.Usuario')),
            ],
        ),
    ]
